version: '3'

services:

  app:
    build:
      context: .
      dockerfile: node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    entrypoint: npm start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 3
      timeout: 10s

  json-server:
    build:
      context: .
      dockerfile: json-server/Dockerfile
    ports:
      - "5000:5000" 
    volumes:
      - ./src/db.json:/usr/src/app/db.json
    entrypoint: npm run json-server
    depends_on:
      app:
        condition: service_healthy


